name: ci

on:
  # Trigger the workflow on push to master or develop, except tag creation
  push:
    branches:
      - 'master'
      - 'develop'
    tags-ignore:
      - '**'

  # Trigger the workflow on pull request
  pull_request: ~

  # Trigger the workflow manually
  workflow_dispatch: ~

jobs:
  # Build and test this packcage on HPC
  ci-hpc:
    name: ci-hpc
    uses: ./.github/workflows/reusable-ci-hpc.yml
    with:
      eccodes-python: ecmwf/eccodes-python@${{ github.event.pull_request.head.sha || github.sha }}
    secrets: inherit